### ISSUE TITLE
Interface mangler options - diverse fejl

### ISSUE THREAD

**Issue by dgh81** [simon-stentoft/ResurseSpil#2]
Man kan ikke læse sig til hvordan man køber farmers etc. (jeg kan se i koden at man skal skrive fx buygoldfarmer.)

Jeg får ingen fejl hvis jeg prøver at købe farmers men ikke har penge.

Udfor teksten der fremkommer når man skriver "status", står der "Metal: 119. Income: 1 wood every 10 seconds." Her skal der nok stå "guld" og ikke "wood".

**Comment by simon-stentoft** [comment]
Rettede stavefejlen. Men ellers tror jeg det er fint, man kan læse hvordan man køber farmers ved at skrive farmers. 
Og testede lige at forsøge at købe alle de forskellige farmers uden at have resurserne til det, men oplevede ikke nogen fejl. [https://i.imgur.com/g43CnCo.png](url)
